#!/usr/bin/env python3
"""
make_web_config.py — write web/config.js so the map reads from Supabase.

Emits ONLY the publishable key, which is designed to be public: it is shipped
to every browser that opens the page, and row level security is what actually
protects the data. The service key must never end up in a web page — it
bypasses RLS entirely.

Without config.js the map falls back to the generated files in output/, so it
still works offline.

Usage:
    python parsers/make_web_config.py
    python parsers/make_web_config.py --remove    # back to reading local files
"""

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent            # BitNBuild/
REPO = ROOT.parent            # repo root
ENV_FILE = REPO / ".env"
OUT = ROOT / "web" / "config.js"


def load_env(path):
    if not path.exists():
        sys.exit(f"No .env at {path}")
    env = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        env[k.strip()] = v.strip().strip('"').strip("'")
    return env


def main():
    ap = argparse.ArgumentParser(description="Generate web/config.js from .env")
    ap.add_argument("--remove", action="store_true",
                    help="Delete config.js so the map reads local files again")
    args = ap.parse_args()

    if args.remove:
        if OUT.exists():
            OUT.unlink()
            print(f"removed {OUT.name} — the map will read ../output/ again")
        else:
            print("config.js already absent")
        return

    env = load_env(ENV_FILE)
    url = env.get("SUPABASE_URL", "")
    key = env.get("SUPABASE_PUBLISHABLE_KEY", "")
    if not url or not key:
        sys.exit("SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY must be set in .env")
    if key == env.get("SUPABASE_SECRET_KEY"):
        sys.exit("refusing to write the service key into a web page")

    OUT.write_text(
        "// Generated by parsers/make_web_config.py — do not edit, do not commit.\n"
        "// The publishable key is public by design; RLS is what protects the data.\n"
        "window.SUPABASE_CONFIG = " + json.dumps({"url": url, "key": key}, indent=2) + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(REPO)} -> {url}")
    print("the map will now read from Supabase; --remove reverts to local files")


if __name__ == "__main__":
    main()
